# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up Snyk to analyze the full Snyk platform (Snyk Open Source, Snyk Code,
# Snyk Container and Snyk Infrastructure as Code)
# The setup installs the Snyk CLI - for more details on the possible commands
# check https://docs.snyk.io/snyk-cli/cli-reference
# The results of Snyk Code are then uploaded to GitHub Security Code Scanning
#
# In order to use the Snyk Action you will need to have a Snyk API token.
# More details in https://github.com/snyk/actions#getting-your-snyk-token
# or you can signup for free at https://snyk.io/login
#
# For more examples, including how to limit scans to only high-severity issues
# and fail PR checks, see https://github.com/snyk/actions/

name: Snyk Security

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@v4
        with:
          version: latest

      - name: Snyk Code test → SARIF
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_API: https://api.eu.snyk.io

        run: |
          set -euo pipefail
          rc=0
          # Write SARIF to a file; allow exit 1 (issues found) but warn on real errors
          snyk code test --sarif > snyk-code.sarif || rc=$?
          if [ "$rc" -eq 2 ]; then
            echo "::error::Snyk Code encountered an error (exit 2). Printing debug…"
            snyk --version
            snyk code test -d || true
            # Keep job green so we can still inspect logs, but surface a warning
            echo "::warning::Proceeding without reliable SARIF due to Snyk error."
          fi

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
